### ISSUE TITLE
로그아웃 시 FCM 토큰 정보도 삭제해주어야 할 것 같아요!

### ISSUE THREAD

**Issue by seohyun-kim** [inu-appcenter/inu-events-android#13]
로그아웃을 해도 알림설정 해 둔게 있으면 푸시 알림이 갑니다...

로그인 시 fcm이 등록될 텐데 로그아웃 할 때 `[POST] fcm/token` 으로  빈 값으로 업데이트 한 번 부탁드리겠습니다.

![image](https://user-images.githubusercontent.com/61939286/201517411-d3c02a1a-d0bb-4deb-b3f7-5efe2439b89a.png)

**Comment by seohyun-kim** [comment]
나중에 편하실 때 부탁드립니다 :)

**Comment by jhg3410** [comment]
수정했습니다~!
