### ISSUE TITLE
신청링크 주르륵 흐르게 수정 가능할까요??

### ISSUE THREAD

**Issue by seohyun-kim** [inu-appcenter/inu-events-android#14]
현재는 이렇게 잘려있는데, 
이게 링크 주소의 경우는 그냥 클릭으로 접속해서 크게 상관이 없었으나,
이렇게 신청 장소를 안내하는 형태는 전체 내용이 보여야 좋을 것 같습니다!!

그리고 혹시 `신청링크` 대신 오프라인 장소나 링크를 포괄할 수 있는 `신청장소`로 바꾸는게 어떠실지도 얘기해봐요!!

![image](https://user-images.githubusercontent.com/61939286/209070019-280e481d-8c63-47e2-a35b-8afbe3da0351.png)

**Comment by jhg3410** [comment]
완료~~
흐르게 하고/ 링크 장소 구분했습니다~~
